name: first

on: [push]

jobs:

  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: echo date
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: "Get-Date"
  job3:
      name: Third job
      runs-on: macos-latest
      needs: [job1, job2]
      steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: date '+Today is %A, %B %d, %Y.'
  job4:
      name: Fourth job
      runs-on: ubuntu-latest
      needs: [job1, job2, job3]
      steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: cal 2021